#-----------------------AUTHORIZATION----------------------
### Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username":"meettg2014@gmail.com",
    "password":"password"
}

### logout
POST http://localhost:5000/auth/logout

### refresh token
POST http://localhost:5000/auth/refresh-token



# ---------- USER------------------------------------------
### Create user
POST http://localhost:5000/user
Content-Type: application/json

{
    "firstName":"John",
    "lastName":"Doe",
    "email":"meettg2014@gmail.com",
    "password":"password",
    "phone":"090645362563"
    
}

### Verify user
POST http://localhost:5000/user/verify
Content-Type: application/json

{
    "email":"meettg2014@gmail.com",
    "otp":"493871"
}

#---------------------TRANSACTION-----------------------------------
### summary
GET http://localhost:5000/trxn/summary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjkyZWEzODVmMGU5YmQ2ZmYxNjhkMSIsInVzZXJuYW1lIjoibWVldHRnMjAxNEBnbWFpbC5jb20iLCJpYXQiOjE3Mjc2MjI0OTUsImV4cCI6MTcyNzYyMzA5NX0.Uk5ewmFjoxp4OKzkNNCnCfpdic8qQYva6FI1CeDWkrM

### income
POST http://localhCxmeXCJ9I0Vl8Wt6lfvzobn_M27pQnm1UHo6ost:5000/trxn/income
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjkyZWEzODVmMGU5YmQ2ZmYxNjhkMSIsInVzZXJuYW1lIjoibWVldHRnMjAxNEBnbWFpbC5jb20iLCJpYXQiOjE3Mjc2MjAzMzEsImV4cCI6MTcyNzYyMDM5MX0.AQu3Bq8DZdgJEiE0pmtPKfJvLEQ3gQ8dn8SzYHqa5vM
Content-Type: application/json

{
    "amount":"2000",
    "date":"2024-09-29:14:40", 
    "category":"Clothes"
}


### income
POST http://localhost:5000/trxn/expenses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjkyZWEzODVmMGU5YmQ2ZmYxNjhkMSIsInVzZXJuYW1lIjoibWVldHRnMjAxNEBnbWFpbC5jb20iLCJpYXQiOjE3Mjc2MjAzMzEsImV4cCI6MTcyNzYyMDM5MX0.AQu3Bq8DZdgJEiE0pmtPKfJvLEQ3gQ8dn8SzYHqa5vM
Content-Type: application/json

{
    "amount":"2000",
    "date":"2024-09-29:10:50", 
    "category":"Electricity"
}

### all-income
GET http://localhost:5000/trxn/all-income
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjkyZWEzODVmMGU5YmQ2ZmYxNjhkMSIsInVzZXJuYW1lIjoibWVldHRnMjAxNEBnbWFpbC5jb20iLCJpYXQiOjE3Mjc2MDg4MDB9.vg6nC0m0AN8vcQOzJ3ccs_DzpXzHmmn7HI_R9WYL8fc

### all-expenses
GET http://localhost:5000/trxn/all-expenses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjkyZWEzODVmMGU5YmQ2ZmYxNjhkMSIsInVzZXJuYW1lIjoibWVldHRnMjAxNEBnbWFpbC5jb20iLCJpYXQiOjE3Mjc2MDg4MDB9.vg6nC0m0AN8vcQOzJ3ccs_DzpXzHmmn7HI_R9WYL8fc
